[PHP]
memory_limit = 256M
upload_max_filesize = 20M
post_max_size = 25M
max_execution_time = 60
date.timezone = UTC
expose_php = Off

; Error Handling
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /dev/stderr

; Security & Performance
variables_order = "EGPCS"
request_order = "GP"
output_buffering = 4096
implicit_flush = Off
zlib.output_compression = Off
